import {describe, expect, it} from 'vitest';

import {
  canonicalJson,
  frozenRuntimeAttestation,
  frozenScientificRuntimeSchema,
} from '../../scripts/frozen-runtime-baseline.mjs';

const manifest = {
  schema_version: frozenScientificRuntimeSchema,
  interpreter: {implementation: 'CPython', version: [3, 12, 4]},
  platform: {system: 'Windows', machine: 'AMD64'},
  required_modules: ['fsspec', 'h5netcdf', 'matplotlib', 'numpy', 'xarray', 'zarr'],
  distributions: [
    {name: 'h5netcdf', version: '1.3.0', direct_url: 'https://example.test/repo', editable: false},
    {name: 'numpy', version: '2.0.0'},
  ],
  native_runtime: {hdf5: '1.14.3', netcdf: '4.9.2'},
};

describe('frozen scientific runtime baseline', () => {
  it('hashes an ordered, path-free manifest with Python-compatible canonical JSON', () => {
    const attestation = frozenRuntimeAttestation(manifest);
    expect(attestation).toEqual({
      schema_version: frozenScientificRuntimeSchema,
      // Generated by Python's json.dumps(..., ensure_ascii=True, separators=(',', ':'), sort_keys=True).
      fingerprint_sha256: '47d86a0d295c1a1794b52c2ee4b325649cdd31eb779d5f74091e25afb771ae3d',
      dependency_count: 2,
    });
    expect(canonicalJson({...manifest, platform: {...manifest.platform, machine: 'M\u00e9tal'}})).toContain('M\\u00e9tal');
    expect(JSON.stringify(manifest)).not.toContain('executable');
  });

  it('rejects unordered modules, dependency drift, and an install-path field', () => {
    expect(() => frozenRuntimeAttestation({...manifest, required_modules: ['numpy', 'h5netcdf']})).toThrow('module list');
    expect(() => frozenRuntimeAttestation({...manifest, distributions: [...manifest.distributions].reverse()})).toThrow('not ordered');
    expect(() => frozenRuntimeAttestation({
      ...manifest,
      interpreter: {...manifest.interpreter, executable: 'C:\\private\\python.exe'},
    })).toThrow('interpreter record');
    expect(() => frozenRuntimeAttestation({
      ...manifest,
      distributions: [{...manifest.distributions[0], source_path: '/private/build'}],
    })).toThrow('distributions');
  });
});
