"""Export Protocol v2 JSON Schema and generated TypeScript declarations."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from oceanx.protocol.v2.models import EVENT_ADAPTER, REQUEST_ADAPTER


def request_schema() -> dict[str, Any]:
    """Return the schema emitted directly by the Pydantic request union."""

    return REQUEST_ADAPTER.json_schema()


def event_schema() -> dict[str, Any]:
    """Return the schema emitted directly by the Pydantic event union."""

    return EVENT_ADAPTER.json_schema()


def _ref_name(reference: str) -> str:
    return reference.rsplit("/", maxsplit=1)[-1]


def _typescript_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return _ref_name(str(schema["$ref"]))
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    for union_key in ("anyOf", "oneOf"):
        if union_key in schema:
            return " | ".join(_typescript_type(option) for option in schema[union_key])
    raw_type = schema.get("type")
    if isinstance(raw_type, list):
        return " | ".join(_typescript_type({"type": value}) for value in raw_type)
    if raw_type == "string":
        return "string"
    if raw_type in {"integer", "number"}:
        return "number"
    if raw_type == "boolean":
        return "boolean"
    if raw_type == "null":
        return "null"
    if raw_type == "array":
        return f"Array<{_typescript_type(schema.get('items', {}))}>"
    if raw_type == "object":
        properties = schema.get("properties")
        if isinstance(properties, dict) and properties:
            required = set(schema.get("required", []))
            lines = ["{"]
            for name, property_schema in properties.items():
                optional = "" if name in required else "?"
                lines.append(
                    f"  {json.dumps(name)}{optional}: {_typescript_type(property_schema)};"
                )
            lines.append("}")
            return "\n".join(lines)
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"Record<string, {_typescript_type(additional)}>"
        if additional is True:
            return "Record<string, unknown>"
        return "Record<string, never>"
    return "unknown"


def _interface_from_definition(name: str, definition: dict[str, Any]) -> str:
    if definition.get("type") != "object":
        return f"export type {name} = {_typescript_type(definition)};"
    properties = definition.get("properties", {})
    required = set(definition.get("required", []))
    lines = [f"export interface {name} {{"]
    for property_name, property_schema in properties.items():
        optional = "" if property_name in required else "?"
        lines.append(
            f"  {json.dumps(property_name)}{optional}: {_typescript_type(property_schema)};"
        )
    lines.append("}")
    return "\n".join(lines)


def _merge_definitions(*schemas: dict[str, Any]) -> dict[str, dict[str, Any]]:
    merged: dict[str, dict[str, Any]] = {}
    for schema in schemas:
        definitions = schema.get("$defs", {})
        if not isinstance(definitions, dict):
            continue
        for name, definition in definitions.items():
            if not isinstance(definition, dict):
                continue
            existing = merged.get(name)
            if existing is not None and existing != definition:
                raise ValueError(f"Conflicting schema definition for {name}")
            merged[name] = definition
    return merged


def _root_union(schema: dict[str, Any]) -> str:
    options = schema.get("oneOf") or schema.get("anyOf") or []
    return " | ".join(_typescript_type(option) for option in options) or "never"


def generate_typescript() -> str:
    """Generate the checked-in frontend contract from Pydantic JSON Schema."""

    requests = request_schema()
    events = event_schema()
    definitions = _merge_definitions(requests, events)
    chunks = [
        "// Generated by scripts/export_protocol_v2.py. Do not edit manually.",
        "// Source of truth: src/oceanx/protocol/v2/models.py.",
        "",
    ]
    for name in sorted(definitions):
        chunks.extend([_interface_from_definition(name, definitions[name]), ""])
    chunks.extend(
        [
            f"export type OceanRequest = {_root_union(requests)};",
            "",
            f"export type OceanEvent = {_root_union(events)};",
            "",
        ]
    )
    return "\n".join(chunks)


def repository_root() -> Path:
    """Resolve the source checkout root for checked-in protocol artifacts."""

    return Path(__file__).resolve().parents[4]


def write_protocol_artifacts(
    *,
    schema_directory: Path | None = None,
    typescript_path: Path | None = None,
) -> tuple[Path, Path, Path]:
    """Write stable JSON schemas and the generated TypeScript union."""

    root = repository_root()
    schema_root = schema_directory or root / "protocol" / "v2" / "schema"
    type_path = typescript_path or root / "frontend" / "packages" / "ocean-client" / "src" / "generated" / "protocol-v2.ts"
    schema_root.mkdir(parents=True, exist_ok=True)
    type_path.parent.mkdir(parents=True, exist_ok=True)
    request_path = schema_root / "request-envelope.json"
    event_path = schema_root / "event-envelope.json"
    request_path.write_text(json.dumps(request_schema(), indent=2, sort_keys=True) + "\n", encoding="utf-8")
    event_path.write_text(json.dumps(event_schema(), indent=2, sort_keys=True) + "\n", encoding="utf-8")
    type_path.write_text(generate_typescript(), encoding="utf-8")
    return request_path, event_path, type_path


__all__ = [
    "event_schema",
    "generate_typescript",
    "request_schema",
    "write_protocol_artifacts",
]
